import Head from "next/head";
import styles from "../styles/Home.module.css";

export const getStaticProps = async () => {
  const server = await fetch("http://localhost:3000/api/server");
  const respone = await fetch("http://localhost:5000/api/product");
  const data = await respone.json();

  return {
    props: {
      data,
    },
  };
};

export default function Home({ data }) {
  if ('name' === 'name') {
    console.log(true);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {data.map((curProd) => {
        return (
          <main>
            <div key={curProd._id}>
              <h2 className={styles.title}>{curProd.title}</h2>
            </div>
          </main>

        );
      })}

    </div>
  );
}
